### ISSUE TITLE
Non-JSON content

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-API-Map-Tiles#3]
OpenAPI assumes that the response to a request will be in JSON. That is frequently not the case.  An extension to OpenAPI to support non-JSON schema (including image formats) has been proposed. This extension has been classified as an OAS Draft Feature. As such, it is legal to use in an OpenAPI document but tool support is not required. 

An introduction to this feature and instructions on how to use it should be included in the suite of OGC API standards.

**Comment by chris-little** [comment]
OAS = Open API SPecification

**Comment by joanma747** [comment]
Is this the proposal you are refering to?:

https://github.com/OAI/OpenAPI-Specification/tree/master/proposals/Alternative%20Schema

**Comment by cmheazel** [comment]
Close for now - re-open when a real case comes along.
