### ISSUE TITLE
Is the /api path missing from opf-map-tiles-api.yaml?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/OGC-API-Map-Tiles#8]
All of the other OGC APIs define an `/api` path in their yaml file. 

The path appears to be missing from the opf-map-tiles-api.yaml file.

**Comment by cportele** [comment]
Features does not. See http://docs.opengeospatial.org/DRAFTS/17-069r1.html#_response_2:

> The API definition document describes the API. In other words, there is no need to include the /api operation in the API definition itself.

**Comment by ghobona** [comment]
APIs for Common, Processes and Coverages offer the `/api` path. 
The path helps to make implementations self-describing.
The path will save developers a lot of time because they will always know where to find the API definition.

**Comment by cportele** [comment]
I don't understand. 

If you have the API definition you already know the API definition without a need to have /api documented in it. 

If you do not have the API definition, but you end up at the landing page, you will have a link with rel="service" to find the API definition.

**Comment by ghobona** [comment]
You are right.
I had missed the rel="service" route. 
The `/api` path is not needed.

**Comment by cmheazel** [comment]
Leaving the /api off of the yaml file was an oversight which I will fix.  Whether it is mandatory or not is debatable.  Just because you have an OpenAPI document doesn't mean it is current and complete.  /api is the authoritative source.

**Comment by cmheazel** [comment]
Fixed and merged into the June 20 branch.
