### ISSUE TITLE
Possible copy and paste errors in the path summaries

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/OGC-API-Map-Tiles#9]
The ones in bold might be copy and paste errors.

* Path = /
**  landing page
* Path = /conformance
**  information about specifications that this API conforms to
* Path = /collections
**  the collections in the dataset
* Path = /collections/{collectionId}
**  describe a collection
* Path = /collections/{collectionId}/queryables
**  fetch the queryable properties of the feature collection
* Path = /collections/{collectionId}/items
**  retrieve features of the feature collection
* Path = /collections/{collectionId}/items/{featureId}
**  fetch a feature
* Path = /tileMatrixSet
**  fetch all available tile matrix sets (tiling schemes)
* Path = /tileMatrixSet/{tileMatrixSetId}
**  fetch a tiling scheme by id
* Path = /tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}
**  retrieve a tile of the dataset
* Path = /collections/{collectionId}/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}
**  fetch a tile of the collection with or without style
* Path = /tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}/info
**  fetch information on a point of a tile of the collection with or without style
* Path = /collections/{collectionId}/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}/info
**  fetch information of a point in a tile of the collection with or without style
* Path = /tiles/{tileMatrixSetId}
**  fetch tiles from several collections.
* Path = /collections/{collectionId}/tiles/{tileMatrixSetId}
**  fetch tiles of a collection
* Path = /map
**  fetch a map of collections with or without style
* Path = /collections/{collectionId}/map
**  **fetch a maps from the collection with or without style**
* Path = /map/info
**  **fetch a maps from the collection with or without style**
* Path = /collections/{collectionId}/map/info
**  **fetch a maps from the collection with or without style**

**Comment by joanma747** [comment]
It has been fixed in the swagger original file https://app.swaggerhub.com/apis/joanma747/opf-map-tiles-api/1.0.0. It will be updated soon based on this file. Thanks
